name: Auto-Merge Stale Deletion PRs

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      - name: Fetch PRs older than 7 days
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "🔍 Looking for stale PRs to auto-merge..."
          today=$(date -u +%s)

          gh pr list --state open --label "stale-profile" --json number,createdAt,title,url \
            --jq '.[] | select(.title | test("Stale Developer Profile Removal"))' |
          jq -c '.' |
          while read -r pr; do
            created=$(echo "$pr" | jq -r '.createdAt')
            created_sec=$(date -d "$created" +%s)
            diff_days=$(( (today - created_sec) / 86400 ))

            if [ "$diff_days" -ge 7 ]; then
              pr_number=$(echo "$pr" | jq -r '.number')
              pr_url=$(echo "$pr" | jq -r '.url')
              echo "✅ Auto-merging PR #$pr_number ($diff_days days old)"
              gh pr merge "$pr_number" --squash --delete-branch --admin
            else
              echo "⏳ Skipping PR created $diff_days days ago"
            fi
          done
